baseURL = "https://xbn.dev"
title = "xbn.dev"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  [params.homeInfoParams]
    Title = "Привет \U0001F44B"    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/khoben"
  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/xbndev"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:me@xbn.dev"

[caches]
  [caches.images]
    dir = ':cacheDir/images'