baseURL = "https://xbn.dev"
title = "xbn.dev"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    manifest = "/site.webmanifest"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  [params.homeInfoParams]
    Title = "Привет \U0001F44B"    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/khoben"
  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/xbndev"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:me@xbn.dev"

[caches]
  [caches.images]
    dir = ':cacheDir/images'